// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/malytinKonstantin/go-fiber/internal/app"
	"github.com/malytinKonstantin/go-fiber/internal/db"
	"github.com/malytinKonstantin/go-fiber/internal/user"
)

import (
	_ "github.com/lib/pq"
	_ "github.com/malytinKonstantin/go-fiber/docs"
)

// Injectors from wire.go:

func InitializeApp(databaseURL string) (*app.App, error) {
	pool, err := db.NewPostgresPool(databaseURL)
	if err != nil {
		return nil, err
	}
	userRepository := user.NewUserRepository(pool)
	userService := user.NewUserService(userRepository)
	userController := user.NewUserController(userService)
	module := user.NewModule(userController)
	sqlDB := db.NewSQLDB(pool)
	appApp := app.NewApp(module, sqlDB)
	return appApp, nil
}

// wire.go:

var PostgresSet = wire.NewSet(db.NewPostgresPool, db.NewSQLDB)

var AppSet = wire.NewSet(
	PostgresSet, app.NewApp, user.NewModule, user.NewUserController, user.NewUserService, user.NewUserRepository,
)
