// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"database/sql"
	"github.com/malytinKonstantin/go-fiber/internal/app"
	"github.com/malytinKonstantin/go-fiber/internal/user"
)

import (
	_ "github.com/lib/pq"
)

// Injectors from wire.go:

func InitializeApp(db *sql.DB) (*app.App, error) {
	userRepository := user.NewUserRepository(db)
	userService := user.NewUserService(userRepository)
	userController := user.NewUserController(userService)
	module := user.NewModule(userController)
	appApp := app.NewApp(module, db)
	return appApp, nil
}
