// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	DeleteUser(ctx context.Context, id int32) error
	GetUser(ctx context.Context, id int32) (Users, error)
	GetUserByUsername(ctx context.Context, username string) (Users, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]Users, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (Users, error)
}

var _ Querier = (*Queries)(nil)
